# Generated by Django 5.1.7 on 2025-04-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='last_data_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(blank=True, choices=[('police', 'Police Department'), ('sheriff', 'Sheriff Department'), ('state', 'State Law Enforcement'), ('federal', 'Federal Agency'), ('campus', 'Campus Police'), ('transit', 'Transit Police'), ('other', 'Other Law Enforcement')], max_length=50, null=True),
        ),
    ]
