# Generated by Django 5.1.7 on 2025-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_add_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_type',
            field=models.CharField(blank=True, choices=[('police', 'Police Department(local law enforcement)'), ('kps', 'Kenya Police Service (KPS)'), ('nis', 'National Intelligence Service (NIS)'), ('dci', 'Directorate of Criminal Investigations (DCI)'), ('other', 'Other Law Enforcement')], max_length=50, null=True),
        ),
    ]
