# Generated by Django 5.1.7 on 2025-05-06 20:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_analytics', '0002_crimeincident_crimetrend'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimePredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('crime_type', models.CharField(max_length=100)),
                ('probability', models.FloatField(help_text='Probability of the predicted crime type (0-1)')),
                ('contributing_factors', models.JSONField(default=dict, help_text='Factors contributing to the prediction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Crime Prediction Results',
                'ordering': ['-prediction_date'],
            },
        ),
    ]
