# Generated by Django 5.1.7 on 2025-03-17 12:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crimes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('crime_summary', 'Crime Summary Report'), ('trend_analysis', 'Crime Trend Analysis'), ('location_analysis', 'Location-based Analysis'), ('comparative', 'Comparative Report'), ('predictive', 'Predictive Analysis Report'), ('custom', 'Custom Report')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('radius', models.FloatField(blank=True, help_text='Radius in kilometers', null=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_map', models.BooleanField(default=True)),
                ('include_recommendations', models.BooleanField(default=False)),
                ('chart_types', models.JSONField(default=list, help_text='List of chart types to include')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('custom_options', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('crime_types', models.ManyToManyField(blank=True, related_name='reports', to='crimes.crimecategory')),
                ('districts', models.ManyToManyField(blank=True, related_name='reports', to='crimes.district')),
                ('neighborhoods', models.ManyToManyField(blank=True, related_name='reports', to='crimes.neighborhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('text', 'Text Section'), ('chart', 'Chart Section'), ('map', 'Map Section'), ('table', 'Table Section'), ('statistics', 'Statistics Section')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('configuration', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='crime_reports.report')),
            ],
            options={
                'verbose_name_plural': 'Report sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('crime_summary', 'Crime Summary Report'), ('trend_analysis', 'Crime Trend Analysis'), ('location_analysis', 'Location-based Analysis'), ('comparative', 'Comparative Report'), ('predictive', 'Predictive Analysis Report'), ('custom', 'Custom Report')], max_length=50)),
                ('template_data', models.JSONField(default=dict, help_text='Template configuration')),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Report templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('analysis_type', models.CharField(max_length=50)),
                ('configuration', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, help_text='1-7 (Monday-Sunday)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='1-31', null=True)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses')),
                ('parameters_override', models.JSONField(blank=True, default=dict, help_text='Override template parameters', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='crime_reports.reporttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scheduled reports',
                'ordering': ['name'],
            },
        ),
    ]
