# Generated by Django 5.1.7 on 2025-03-17 12:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity_level', models.IntegerField(default=1)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='crimes.crimecategory')),
            ],
            options={
                'verbose_name_plural': 'Crime categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('solved', 'Solved'), ('closed', 'Closed'), ('unfounded', 'Unfounded')], default='reported', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('block_address', models.CharField(max_length=255)),
                ('is_violent', models.BooleanField(default=False)),
                ('property_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weapon_used', models.BooleanField(default=False)),
                ('weapon_type', models.CharField(blank=True, max_length=100, null=True)),
                ('drug_related', models.BooleanField(default=False)),
                ('domestic', models.BooleanField(default=False)),
                ('arrests_made', models.BooleanField(default=False)),
                ('gang_related', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='agencies.agency')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='crimes.crimecategory')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='CrimeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='crimes.crime')),
            ],
            options={
                'verbose_name_plural': 'Crime media',
            },
        ),
        migrations.CreateModel(
            name='CrimeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crimes.crime')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='agencies.agency')),
            ],
            options={
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='crime',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crimes', to='crimes.district'),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='crimes.district')),
            ],
            options={
                'verbose_name_plural': 'Neighborhoods',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='crime',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crimes', to='crimes.neighborhood'),
        ),
        migrations.CreateModel(
            name='CrimeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('violent_count', models.IntegerField(default=0)),
                ('property_damage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arrests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='agencies.agency')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='crimes.crimecategory')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='crimes.district')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='crimes.neighborhood')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'category', 'district', 'neighborhood', 'agency')},
            },
        ),
        migrations.AddIndex(
            model_name='crime',
            index=models.Index(fields=['date'], name='crimes_crim_date_0ea517_idx'),
        ),
        migrations.AddIndex(
            model_name='crime',
            index=models.Index(fields=['status'], name='crimes_crim_status_c84e66_idx'),
        ),
        migrations.AddIndex(
            model_name='crime',
            index=models.Index(fields=['is_violent'], name='crimes_crim_is_viol_05079a_idx'),
        ),
        migrations.AddIndex(
            model_name='crime',
            index=models.Index(fields=['agency'], name='crimes_crim_agency__1693ba_idx'),
        ),
        migrations.AddIndex(
            model_name='crime',
            index=models.Index(fields=['category'], name='crimes_crim_categor_a253a9_idx'),
        ),
    ]
