# Generated by Django 5.1.7 on 2025-05-02 20:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0002_alter_crime_location_alter_district_boundary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='boundary',
        ),
        migrations.AddField(
            model_name='district',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
